#let python do the paint job

from turtle import *
import random

list = [forward,left,right]
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))
random.choice(list)(random.randint(0,100))

